package com.bytesgo.nfs.rpc.codec.protobuf;

import com.bytesgo.nfs.rpc.codec.CodecException;
import com.bytesgo.nfs.rpc.codec.Encoder;
/**
 * nfs-rpc Apache License
 * 
 * http://code.google.com/p/nfs-rpc (c) 2011
 */
import com.google.protobuf.Message;

/**
 * ProtocolBuf Encoder
 * 
 * @author <a href="mailto:bluedavy@gmail.com">bluedavy</a>
 */
public class ProtobufEncoder implements Encoder {

	public byte[] encode(Object object) throws CodecException {
		if (!(object instanceof Message)) {
			throw new CodecException(
					"Send object is not type of com.google.protobuf.Message,pls sure the object is generated by pb,object is: "
							+ object);
		}
		Message message = (Message) object;
		return message.toByteArray();
	}

}
